# Jekyll main configuration file
# See https://jekyllrb.com/docs/configuration/ for further customization options
# Defaults settings https://jekyllrb.com/docs/configuration/#default-configuration

title: Configuring Ollama and Continue VS Code Extension for Local Coding Assistant
description: "Learn to configure Codellama and VSCode so that you can get autocompletion without calling any API!"

permalink: date # how your URLs are built, see https://jekyllrb.com/docs/permalinks/#builtinpermalinkstyles

plugins:
  - jekyll-default-layout

remote_theme: just-the-docs

# timezone: America/Los_Angeles # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# theme: minima 
# look for themes on https://github.com/topics/jekyll-theme and https://rubygems.org/search?utf8=%E2%9C%93&query=jekyll-theme

# Files to excludes from your website
# exclude:  
# - .gitignore
# - CNAME 

